name: Postman Collection Workflow

on:
  push: 
    branches: [main]

  workflow_dispatch: 
  schedule:
    - cron: '30 02 * * *' # 8 AM IST everyday
    - cron: '00 02 * * *' # 7:30 PM IST everyday
    - cron: '00 06 * * 1-5' # 11:30 AM IST everyday


jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.1

      - name: Insatll Nodejs and npm
        uses: actions/setup-node@v6.3.0
        with:
          node-version: '22'

      - name: Install Newman and HTML Extra globally
        run: | 
              npm install -g newman
              npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with newman
        run: |
               newman run Inwarranty-flow-Collection.postman_collection.json \
               -e QA.postman_environment.json \
               -r cli,htmlextra

      - name: Upload a Newman Run Artifact
        if: always()
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Postman Collection Newman Report
          path: newman/*.html
